Traceback (most recent call last):
  File "/Users/sarahbentley/.julia/conda/3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/sarahbentley/.julia/conda/3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sarahbentley/dfa_transformer/src/GPT/train.py", line 119, in <module>
    main(args)
  File "/Users/sarahbentley/dfa_transformer/src/GPT/train.py", line 95, in main
    model = GPT(gptconf).to(device)
  File "/Users/sarahbentley/dfa_transformer/src/GPT/GPT.py", line 125, in __init__
    h = nn.ModuleList([Block(config) for _ in range(config.n_layer)]),
  File "/Users/sarahbentley/dfa_transformer/src/GPT/GPT.py", line 125, in <listcomp>
    h = nn.ModuleList([Block(config) for _ in range(config.n_layer)]),
  File "/Users/sarahbentley/dfa_transformer/src/GPT/GPT.py", line 104, in __init__
    self.attn = CausalSelfAttention(config)
  File "/Users/sarahbentley/dfa_transformer/src/GPT/GPT.py", line 35, in __init__
    assert config.n_embd % config.n_head == 0
AssertionError